version: "3.8"
services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    command: ["/bin/sh", "-c", "until curl -s http://127.0.0.1:11434 >/dev/null; do echo 'Waiting for Ollama API...'; sleep 1; done; echo 'Ollama API is up. Running deepseek...'; ollama run deepseek-r1:7b"]
    restart: unless-stopped

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    ports:
      - "3000:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

volumes:
  ollama:
  open-webui:
